
// Objective-C API for talking to the following Go packages
//
//	github.com/netsec-ethz/scion-apps/pkg/appnet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Appnet_FRAMEWORK_H__
#define __Appnet_FRAMEWORK_H__

#include "Appnet.objc.h"
#include "Universe.objc.h"

#endif
